import = [
  "/usr/lib/node_modules/alacritty-themes/themes/IR-Black.toml"
]

[font]
size = 15 

  [font.normal]
  family = "FiraCode Nerd Font"

[window]
opacity = 1

  [window.padding]
  x = 2
  y = 2
